#*****************************************************************************
# @file    prj.conf
# @author  Karol Stefanik
# @brief   Project configuration for nrf-info-board client (Zephyr RTOS)
#
# Copyright (c) 2025 Karol Stefanik
# SPDX-License-Identifier: Apache-2.0
#*****************************************************************************

# GPIO and logging
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y

# Networking and sockets
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=n
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y

# Modem and LTE
CONFIG_NRF_MODEM_LIB=y
CONFIG_LTE_LINK_CONTROL=y
CONFIG_LTE_NETWORK_MODE_LTE_M=y
CONFIG_LTE_CONNECT_TIMEOUT_S=30

# PSM
CONFIG_LTE_PSM_REQ=y
CONFIG_LTE_PSM_REQ_RPTAU="00000001" #TAU=1 hour
CONFIG_LTE_PSM_REQ_RAT="00000100"   #Active Time=4 seconds
CONFIG_LTE_PROPRIETARY_PSM_REQ=y

# Notifications
CONFIG_LTE_LC_MODEM_SLEEP_NOTIFICATIONS=y
CONFIG_LTE_LC_TAU_PRE_WARNING_NOTIFICATIONS=y

# MQTT configuration
CONFIG_MQTT_LIB=y
CONFIG_MQTT_CLEAN_SESSION=y
CONFIG_MQTT_BROKER_HOSTNAME="mqtt.nordicsemi.academy"
CONFIG_MQTT_BROKER_PORT=1883
CONFIG_MQTT_STATUS_TOPIC="info-board/status"
CONFIG_MQTT_CMD_TOPIC="info-board/command"
CONFIG_MQTT_DISPLAY_TOPIC="info-board/display"

# MQTT keepalive interval (in seconds).
CONFIG_MQTT_KEEPALIVE=1200

# How often should the modem wake up to send data (in seconds)
CONFIG_WAKEUP_TIMER_PERIOD_SECONDS=180

# Memory pool
CONFIG_HEAP_MEM_POOL_SIZE=8192

# Thread priorities and stack sizes
CONFIG_LTE_THREAD_PRIORITY=2
CONFIG_LTE_THREAD_STACK_SIZE=2048
CONFIG_MQTT_THREAD_PRIORITY=3
CONFIG_MQTT_THREAD_STACK_SIZE=4096
CONFIG_DISPLAY_THREAD_PRIORITY=4
CONFIG_DISPLAY_THREAD_STACK_SIZE=6144

# Display configuration
CONFIG_DISPLAY=y
CONFIG_SSD16XX=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=y

# Power management
CONFIG_PM_DEVICE=y